name: pass_emploi_app
description: Pass Emploi iOS and Android app.

publish_to: "none"
version: 3.19.0

environment:
  sdk: 3.5.3 # Dart version
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  # Dart
  collection: "1.18.0"
  equatable: "2.0.5"
  synchronized: "3.1.0+1"
  uuid: "3.0.7" # Bump to 4.3.3 or greater when matomo_tracker > 4.1.1 is published.
  clock: "1.1.1"
  # Dio
  dio: "5.4.2"
  dio_cache_interceptor: "3.5.0"
  dio_cache_interceptor_file_store: "1.2.3"
  http_parser: "4.0.2"
  # Firebase
  firebase_core: "2.27.2"
  firebase_crashlytics: "3.4.20"
  firebase_remote_config: "4.3.19"
  firebase_messaging: "14.7.21"
  firebase_auth: "4.18.0"
  firebase_app_installations: "0.2.4+19"
  cloud_firestore: "4.15.10"
  # UI
  flutter_svg: "2.0.10+1"
  smooth_page_indicator: "1.1.0"
  path_provider: "2.1.2"
  flutter_staggered_animations: "1.1.1"
  shimmer: "3.0.0"
  confetti: "0.7.0"
  dotted_border: "2.1.0"
  flutter_linkify: "6.0.0"
  # Native features
  webview_flutter: "4.10.0"
  flutter_local_notifications: "17.2.2"
  flutter_appauth: "6.0.5"
  flutter_secure_storage: "9.0.0"
  url_launcher: "6.2.5"
  share_plus: "8.0.2"
  open_filex: "4.4.0"
  in_app_review: "2.0.9"
  flutter_timezone: "1.0.8"
  connectivity_plus: "6.0.1"
  image_picker: "1.0.7"
  flutter_image_compress: "2.2.0"
  file_picker: "8.0.3"
  app_settings: "5.1.1"
  # Others
  flutter_redux: "0.10.0"
  redux: "5.0.0"
  flutter_dotenv: "5.1.0"
  package_info_plus: "4.2.0" # Bump to 6.0.0 or greater when matomo_tracker > 4.1.1 is published.
  encrypt: "5.0.1" # Version 5.0.3 makes 1 test crash
  logger: "2.2.0"
  matomo_tracker: "4.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Assets generation
  flutter_native_splash: "2.4.0"
  flutter_launcher_icons: "0.13.1"
  # Test
  mocktail: "1.0.3"
  http_mock_adapter: "0.6.1"
  async: "2.11.0"
  # Static analysis
  flutter_lints: "3.0.1"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tuto/
    - assets/onboarding/
    - assets/illustrations/
    - assets/boite_a_outils/
    - assets/benevolat/
    - assets/cje/
    - assets/mode_demo/
    - assets/mode_demo/brsa/
    - assets/mode_demo/cej/
    - env/

  fonts:
    - family: AppIconsAdditional
      fonts:
        - asset: fonts/AppIconsAdditional.ttf
    - family: Marianne
      fonts:
        - asset: fonts/Marianne-Regular.otf
        - asset: fonts/Marianne-Regular.otf
          weight: 400
        - asset: fonts/Marianne-Medium.otf
          weight: 500
        - asset: fonts/Marianne-Bold.otf
          weight: 700
