name: pass_emploi_app
description: Pass Emploi iOS and Android app.

publish_to: 'none'
version: 1.4.1

environment:
  sdk: "2.16.2" # Dart version
  flutter: 2.10.5

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: '1.0.3'
  flutter_redux: '0.9.0'
  package_info: '2.0.2'
  flutter_local_notifications: '9.5.0'
  flutter_dotenv: '5.0.2'
  url_launcher: '6.1.0'
  flutter_appauth: '2.4.1+1'
  flutter_linkify: '5.0.2'
  share_plus: '4.0.4'
  flutter_secure_storage: '5.0.2'
  # Dart
  http: '0.13.4'
  http_interceptor: '1.0.2'
  intl: '0.17.0'
  collection: '1.15.0'
  equatable: '2.0.3'
  logger: '1.1.0'
  uuid: '3.0.6'
  # Firebase
  firebase_core: '1.16.0'
  firebase_crashlytics: '2.7.2'
  firebase_remote_config: '2.0.6'
  firebase_messaging: '11.3.0'
  firebase_auth: '3.3.17'
  cloud_firestore: '3.1.14'
  synchronized: '3.0.0+2'
  flutter_cache_manager: '3.3.0'
  # UI
  google_fonts: '2.3.2'
  # Analytics
  matomo:
    git:
      url: https://github.com/BonnetM/dart-matomo.git
      ref: feat/add-outlink-support

  encrypt: '5.0.1'
  smooth_page_indicator: '1.0.0+2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.14.0


flutter:

  uses-material-design: true

  assets:
    - yolo.json
    - assets/mode_demo/yolo.json
    - assets/mode_demo/
    - assets/
    - res/
    - res/mode_demo/
    - res/mode_demo/yolo.json
    - env/

  fonts:
    - family: Marianne
      fonts:
        - asset: fonts/Marianne-Regular.otf
        - asset: fonts/Marianne-Regular.otf
          weight: 400
        - asset: fonts/Marianne-Bold.otf
          weight: 700