name: pass_emploi_app
description: Pass Emploi iOS and Android app.

publish_to: "none"
version: 3.1.0

environment:
  sdk: ">=2.18.2 <4.0.0" # Dart version
  flutter: 3.10.1

dependencies:
  # Flutter
  dotted_border: "2.0.0+2"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: "1.1.6"
  flutter_redux: "0.10.0"
  flutter_local_notifications: "12.0.4"
  flutter_dotenv: "5.0.2"
  flutter_appauth: "2.4.1+1"
  flutter_linkify: "5.0.2"
  flutter_secure_storage: "5.0.2"
  flutter_cache_manager: "3.3.0"
  package_info: "2.0.2"
  url_launcher: "6.1.0"
  share_plus: "4.0.4"
  open_filex: "4.3.1"
  path_provider: "2.0.11"
  smooth_page_indicator: "1.0.0+2"
  in_app_review: "2.0.4"
  webview_flutter: "4.0.5"
  # Dart
  dio: "5.1.0"
  http: "0.13.5"
  http_interceptor: "1.0.2"
  intl: "0.18.0"
  collection: "1.17.1"
  equatable: "2.0.3"
  logger: "1.1.0"
  uuid: "3.0.7"
  synchronized: "3.0.0+2"
  encrypt: "5.0.1"
  matomo_tracker: "2.0.0"
  # Firebase
  firebase_core: "2.13.0"
  firebase_crashlytics: "3.3.1"
  firebase_remote_config: "4.2.1"
  firebase_messaging: "14.6.1"
  firebase_auth: "4.6.1"
  cloud_firestore: "4.7.1"
  firebase_app_installations: "0.2.3+1"
  flutter_native_timezone: "2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.14.0
  mocktail: ^0.3.0
  flutter_native_splash: "2.2.18"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tuto/
    - assets/mode_demo/
    - assets/mode_demo/brsa/
    - assets/mode_demo/cej/
    - env/

  fonts:
    - family: AppIconsAdditional
      fonts:
        - asset: fonts/AppIconsAdditional.ttf
    - family: Marianne
      fonts:
        - asset: fonts/Marianne-Regular.otf
        - asset: fonts/Marianne-Regular.otf
          weight: 400
        - asset: fonts/Marianne-Bold.otf
          weight: 700
