name: pass_emploi_app
description: Pass Emploi iOS and Android app.

publish_to: 'none'
version: 0.2.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_redux: ^0.8.2
  shared_preferences: ^2.0.6
  http: ^0.13.3
  intl: ^0.17.0
  collection: ^1.15.0
  flutter_svg: ^0.22.0
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_crashlytics: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/ic_logo.svg
    - assets/ic_white_check.svg
    - assets/ic_white_circle.svg
    - assets/ic_night_blue_circle.svg
    - assets/ic_paper_plane.svg
    - assets/ic_envelope.svg