name: pass_emploi_app
description: Pass Emploi iOS and Android app.

publish_to: 'none'
version: 1.3.0

environment:
  sdk: "2.16.1" # Dart version
  flutter: 2.10.3

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: '0.22.0'
  flutter_redux: '0.8.2'
  package_info: '2.0.2'
  flutter_local_notifications: '9.4.0'
  flutter_dotenv: '5.0.2'
  url_launcher: '6.0.15'
  flutter_appauth: '2.1.0+1'
  flutter_linkify: '5.0.2'
  share_plus: '3.0.4'
  flutter_secure_storage: '5.0.2'
  # Dart
  http: '0.13.3'
  http_interceptor: '1.0.1'
  intl: '0.17.0'
  collection: '1.15.0'
  equatable: '2.0.3'
  logger: '1.1.0'
  uuid: '3.0.6'
  # Firebase
  firebase_core: '1.10.6'
  firebase_crashlytics: '2.4.4'
  firebase_remote_config: '1.0.3'
  firebase_messaging: '11.2.4'
  cloud_firestore: '3.1.5'
  synchronized: '3.0.0'
  firebase_auth: '3.3.4'
  flutter_cache_manager: '3.3.0'
  # UI
  google_fonts: '2.1.0'
  # Analytics
  matomo:
    git:
      url: https://github.com/BonnetM/dart-matomo.git
      ref: feat/add-outlink-support

  encrypt: '5.0.1'
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.14.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - env/

  fonts:
    - family: Marianne
      fonts:
        - asset: fonts/Marianne-Regular.otf
        - asset: fonts/Marianne-Regular.otf
          weight: 400
        - asset: fonts/Marianne-Bold.otf
          weight: 700